### ISSUE TITLE
Save not working in many situations

### ISSUE THREAD

**Issue by idofperion** [elasticfence/kaae#10]
The UI seams to ignore the save request.

After kibana restart it works again for a while

10x

**Comment by lmangani** [comment]
Hi @idofperion - Thanks for the report and for being an early tester! The save/reload functions are still young indeed. Could you kindly describe your sequence of action, step by step as well as results vs. expected results?

**Comment by lmangani** [comment]
Please update to latest version and try again, existing documents should now update. If you have issues with specific queries, please capture and report any browser console and kibana logs. Thanks!

**Comment by lmangani** [comment]
feel free to reopen if still having issues and thanks again for the report!
