### ISSUE TITLE
Save not saving, by design?

### ISSUE THREAD

**Issue by LazyDBA247-Perion** [elasticfence/kaae#11]
Hi,
first of all 10x! for this great plugin.

when i am in kibana and using the spy buttons (save or save+edit)
the "new" watch is being added to the watchers array, but you don't save it to the watcher index
meaning when i navigate outside of the watcher page, my save is not persistent.
loading the watcher page again, get the "saved" watches from the index and delete the one i just pressed "save" / "save + edit...", this is can be overcome by opening the new watch -> edit -> save, then it is persists to the index....

adding, $scope.watcherSave(0) solves this issue:
$scope.watcherNew(JSON.parse($window.localStorage.getItem('kaae_saved_query')));
**/* adding save to persist the watch, using index 0 as the unshift makes it the first object */
$scope.watcherSave(0);**
$window.localStorage.removeItem('kaae_saved_query');

another option is to call the button, edit and not save :)

10x!

**Comment by lmangani** [comment]
Hi @LazyDBA247-Perion and thanks for the report!

You're indeed right, the current Spy Helper barely caches the new Watcher for temporary editing, but does expect the user to finalize and save it explicitly - you will notice the Delete button is missing too, as an indicator of the alarm not being saved. Two options:

- Rename the buttons as you suggest
- Have the SPY Plugin actually save the alarm mockup

**Comment by LazyDBA247-Perion** [comment]
Hi,
Thanks for the quick response,
i would recommend two changes, if you will change the ID to be auto generated by elasticsearch, and set the watch name to other than the id field, you won't have any issue of overwriting existing watches with a user mistakenly creating the same name for a watch with an old watch name.
and then auto saving the watch from the spy plugin won't be any issue, the only risk is getting duplicate watches, but i prefer getting two mails than getting none :)

because i can edit all aspects of the watch in the spy plugin , i think saving it automatically should be the change , not the label rename, and letting elastic manage the id of the watch and "allowing" duplicate watch name, can give the fail safe of overwriting watch with the "new" auto save feature.

if you do it, need to change the json from the autosave to have _new: false, or will have the orange color always :)

Regards.
Yoni (LazyDBA247)

**Comment by lmangani** [comment]
Good Input! 
The original plan was to try and keep this as compatible as possible with the stock ES Watcher in format, so that's why it comes as you see. I'll try to shape the suggestions into a commit and post updates here, probably letting go of the localstorage cache and pushing the new watcher from the Spy Plugin directly to the KaaE save API

**Comment by lmangani** [comment]
Buttons changed to reflect their function in latest version
