### ISSUE TITLE
Email Integration

### ISSUE THREAD

**Issue by LazyDBA247-Perion** [elasticfence/kaae#12]
Hi,
Can you elaborate on how you plan to have email sending solution?
i understand that sending an email from plug-in/javascript is a issue, usually need some "3rd" party API.

Regards.
Yoni (LazyDBA247)

**Comment by lmangani** [comment]
Hi @LazyDBA247-Perion 
The plan is to use something such as [emailjs](https://github.com/eleith/emailjs) leveraging general delivery configuration per-action type provided by ```kaae.json```

**Comment by lmangani** [comment]
feature still in development but the baseline is in, pending persistent settings.
right now can email/slack settings be controlled editing ```kaae.json``` and restarting kibana

**Comment by lmangani** [comment]
Email delivery is confirmed working on the latest version for both watchers and reports :)
Settings can be cloned and kept in ```/etc/kaae.json``` and no more restarts required to update the schedule. In case of further problems, feel free to reopen this issue.
