### ISSUE TITLE
watcher index is not automatically created on first start

### ISSUE THREAD

**Issue by seuf** [elasticfence/kaae#13]
When kaae app is starting it does not check for the watcher index and nothing is displayed on the home page.

I've noticed a network error on /list url :
```
{statusCode: 404, error: "Not Found",…}
error: "Not Found"
message : "[index_not_found_exception] no such index, with: {"resource.type":"index_or_alias","resource.id":"watcher","index":"watcher"} :: {"path":"/watcher/_search","query":{"allow_no_indices":false},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index\":\"watcher\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index\":\"watcher\"},\"status\":404}"}"
statusCode: 404
```

So I've create a dummy document in a watcher index, and now the page is displayed correctly.
Can you add a test and create the index if it does not exists on the first start ?

**Comment by lmangani** [comment]
Hi @seuf Thanks for the report! We're in early stage so this is very useful. 
I'll add output in case of no watchers found to suggest the user create one

**Comment by LazyDBA247-Perion** [comment]
or maybe in the install explanation, just add a requirement to manually build the index,  maybe an example will help:
curl -XPUT 'http://localhost:9200/watcher/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    }
}'

**Comment by lmangani** [comment]
There's already a function ```function createKaaeIndex``` just need to set it in place... work in progress

**Comment by LazyDBA247-Perion** [comment]
Woo, not resting ;)
Thanks!

**Comment by lmangani** [comment]
https://github.com/elasticfence/kaae/commit/b128bd384b53ec6ca5a7717381d6adfa5101113c should do the job. Could you give it a shot and confirm?

**Comment by LazyDBA247-Perion** [comment]
hi,
i had kaae installed and index already created.
removed old kaae (git) folder, did a "full" install/build (git clone, npm , remove old plugin,  new plugin install)
stop kibana -> deleted all watcher* indexes -> start kibana (no indexes created)
opened kaae (the ui for watchers is empty / without the ability to add, no index created)
tried to use the spy and save new watcher, didn't show the new watcher in kaae plugin)
and index wasn't created.

and better to have 1 shard for small amount of data and 1 replica than 2 shards and 0 replica :)

Regards.

**Comment by lmangani** [comment]
Could you attach the kibana logs?

**Comment by LazyDBA247-Perion** [comment]
hi,
stop kibana -> clean logs -> start kibana
tried to open kaee watchers tab, and tried to save + edit from the spy.

10x!

[kibana.stdout.txt](https://github.com/elasticfence/kaae/files/405296/kibana.stdout.txt)
[kibana.stderr.txt](https://github.com/elasticfence/kaae/files/405297/kibana.stderr.txt)

**Comment by LazyDBA247-Perion** [comment]
Hi,
found the issue, your create command uses name: but should be index:
replacing:
name: config.es.alarm_index,
with
index: config.es.alarm_index,

and now indexes are been created :)

10x!

**Comment by lmangani** [comment]
Excellent! Thank You both guys
