### ISSUE TITLE
Plugin installation was unsuccessful

### ISSUE THREAD

**Issue by daveres** [elasticfence/kaae#17]
1. Issue Description

Error to install plugin in kibana. 

/opt/kibana/bin/kibana plugin --install kaae -u file://`pwd`/kaae-latest.tar.gz
Installing kaae
Attempting to extract from file:///root/kaae/kaae-latest.tar.gz
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "/opt/kibana-4.3.1-linux-x64/installedPlugins/.plugin.installing/init.js:46
                                                                type: 'string',
                                                                ^^^^
Duplicate data property in object literal not allowed in strict mode"

2. Reproducing the Issue step-by-step

git clone https://github.com/chenryn/kaae
cd kaae && npm install && npm run package
/opt/kibana/bin/kibana plugin --install kaae -u file://`pwd`/kaae-latest.tar.gz

3. Expected Results vs. Actual Results

4. Additional Details

Ubuntu 14.04.2 LTS
Kibana Version 4.3.1

**Comment by LazyDBA247-Perion** [comment]
hi,
you should have kibana 4.5+ :)

**Comment by daveres** [comment]
Sorry I missed this information.

A lot of thanks
