### ISSUE TITLE
Bucket alarms

### ISSUE THREAD

**Issue by pekermert** [elasticfence/kaae#18]
I need to create an alarm for bucket doc_count.

I'm trying to create an alarm for this response. When doc_count greater than 3, it must alert for that key. How could i configure the condition section ? 

here is sample response
```
{
    "aggregations": {
        "prices": {
            "buckets": [
                {
                    "key": 0,
                    "doc_count": 5
                },
                {
                    "key": 50,
                    "doc_count": 4
                },
                {
                    "key": 100,
                    "doc_count": 0
                },
                {
                    "key": 150,
                    "doc_count": 3
                }
            ]
        }
    }
}
```

**Comment by lmangani** [comment]
The condition script at this time is simply running the script in eval() for ```true``` or ```false``` returned

Here's a quick fiddle replicating the relevant matching and mustache code and displaying a possible approach with your aggs results: http://jsfiddle.net/mnhw3edn/2/

```
"condition": {
      "script": {
        "script": "\"var match=false;payload.ctx.payload.aggregations.prices.buckets.forEach(function(e){ if(e.doc_count > 3) match=true });match;\""
      }
    }
```

**Comment by pekermert** [comment]
Thanks Lorenzo !
