### ISSUE TITLE
Watcher changes aren't reflecting to alarms

### ISSUE THREAD

**Issue by pekermert** [elasticfence/kaae#19]
I just change watcher and it saved successfully. But changes doesn't reflected to alarms. 

I think watcher update functions doesn't work correct. I edited my watcher configs but alarms are creating for old config. Alarms are updating when i restart kibana.

Kibana version : 4.5.4

Ps : Changes reflected after 10 minutes.

**Comment by lmangani** [comment]
Hi Peter,

In the current alpha rules are loaded on Kibana start/restart, we're working on exposing the full Kaae configuration vs. scheduling with reload on save/edit for individual watchers.

**Comment by pekermert** [comment]
as i mention , changes reflected after 10 minutes. Thanks again Lorenzo.

**Comment by lmangani** [comment]
The mechanism will shortly mature and get triggers - let us know if you have further notes/results.
Thanks a lot for your testing & reports! very much appreciated
