### ISSUE TITLE
Add release for environments without npm

### ISSUE THREAD

**Issue by mterron** [elasticfence/kaae#20]
1. Issue Description
npm is required to install. A tarball could be added to the releases page and installed with kibana -i https://github.com/elasticfence/kaae/master.tar.gz

**Comment by lmangani** [comment]
Hi @mterron and Thanks for your feedback!
The tarball is not yet in place as KaaE is still considered in development and a package might provide the false impression of this being ready for production. The main blocker is the scheduler not reloading, I'll add this feature and an automated build this week as per our other projects/plugins.

**Comment by lmangani** [comment]
temporarily... https://github.com/elasticfence/kaae/releases/tag/snapshot
