### ISSUE TITLE
alarms is listed in ASC or out-of-order?

### ISSUE THREAD

**Issue by chenryn** [elasticfence/kaae#27]
![image](https://cloud.githubusercontent.com/assets/1219655/18805326/df36acaa-823c-11e6-9007-d82f564b1036.png)

**Comment by lmangani** [comment]
TODO: Switch view to Kbn Datatable for displaying results w/ filtering and ordering

**Comment by maxout123** [comment]
This isssue is pretty annoying :(

**Comment by lmangani** [comment]
Could you pull latest and re-test this should be fixed

**Comment by maxout123** [comment]
Unfortunately, it's still out of order

**Comment by lmangani** [comment]
Finally fixed in latest build, required double escaping due to the @ character in the way ;P
Please reopen in case you notice any odd behaviour - we will replace this table with the Kibana one as soon as time allows for proper sorting and filtering.
