### ISSUE TITLE
Can't see more than 10 watchers 

### ISSUE THREAD

**Issue by sunnynew** [elasticfence/kaae#30]
Hi @lmangani 

Currently we can't see more than 10 watchers in KaaE, there is no pagination to travel between pages. Though we can create more than 10 watchers but can't see/modify them.

Feature if we can incorporate:
1). Grouping of watchers -- like one group of watchers related to access log, another group for error logs. This will help manage big list of watchers. 
2). Disable a watcher -- if we want to disable a watcher for sometime, currently we can just increase the schedule time, alter condition to stop alerts. 
3). Alert after number of consecutive failures -- set value to send alert say after 2 consecutive fails, currently KaaE alert just after condition meet.

**Comment by chenryn** [comment]
1. Maybe we need a manual parameter for watcher grouping. Otherwise group by indices-pattern or some may-exists-or-not fields would cause mistakes, I think...
2. disable/enable button is a good idea.
3. inhibition of alert, recover message etc are not about this topic, you may send a new issue?

Anyway, I think we can have a search bar and hits.total number in the webui first.

**Comment by sunnynew** [comment]
Thanks, can we find some work around to increase # of watcher from 10. This is kind of imp for me. Any manual tweek in js files to make it 100

Please reply asap.

**Comment by lmangani** [comment]
@sunnynew check the latest two commits, will push a major improvement for display of results in the coming week

**Comment by sunnynew** [comment]
Hi @lmangani 

Latest two commits just increase Alarms results but not Watchers -- Watchers results remain same at 10

I also manually did change "size":100 from "size":10 earlier which only increased Alarms results. 

Please look to increase **Watchers** results. 

Thanks!

**Comment by sunnynew** [comment]
Hi,

Any quick thoughts to increase # of results before major release next week. I need to quickly create some imp monitors.

Thanks!

**Comment by lmangani** [comment]
@sunnynew should be fixed along a few more buggies in latest version and liked to the same parameter, Please check and confirm if working.

**Comment by lmangani** [comment]
PS: Could you also kindly open a different issue for each feature request? This way we can follow up and implement them.

**Comment by sethyes** [comment]
This appears to be fixed -- I  can now successfully save >10 watchers, which I could not do in prior versions.

**Comment by lmangani** [comment]
Thanks for the confirmation @sunnynew
