### ISSUE TITLE
Kibana stops running once a scheduled report kicks off after reinstall

### ISSUE THREAD

**Issue by sethyes** [elasticfence/kaae#34]
1. Issue Description: Upon uninstall & reinstall of KaaE, a package appears to not fully reinstall correctly, as when a reporter runs, Kibana stops running. 

The following logs elude to the issue;

kibana.stdout

    {"type":"log","@timestamp":"2016-10-06T00:21:00Z","tags":["status","info","KaaE"],"pid":28607,"message":"Executing watch: cluster_health_watch Next Round of cluster_health_watch at Wed Oct 05 2016 18:21:00 GMT-0600 (MDT)"}
    {"type":"log","@timestamp":"2016-10-06T00:21:00Z","tags":["status","debug","KaaE","WATCHER DEBUG"],"pid":28607,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'cluster_health_watch',\n  _score: 1,\n  _source: \n   { trigger: { schedule: [Object] },\n     input: { search: [Object] },\n     condition: { script: [Object] },\n     transform: {},\n     actions: { report_admin: [Object] } } }"}

    {"type":"log","@timestamp":"2016-10-06T00:21:00Z","tags":["status","debug","KaaE"],"pid":28607,"message":"Reloading Watchers..."}
    {"type":"log","@timestamp":"2016-10-06T00:21:00Z","tags":["status","info","KaaE"],"pid":28607,"message":"Executing watch: reporter_misses Next Round of reporter_misses at Wed Oct 05 2016 18:21:00 GMT-0600 (MDT)"}

    {"type":"log","@timestamp":"2016-10-06T00:21:00Z","tags":["status","debug","KaaE","WATCHER DEBUG"],"pid":28607,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'reporter_misses',\n  _score: 1,\n  _source: \n   { trigger: { schedule: [Object] },\n     input: { search: [Object] },\n     condition: {},\n     transform: {},\n     actions: { report_admin: [Object] } } }"}

kibana.stderr:

    Unhandled rejection Error: spawn phantomjs ENOENT
        at exports._errnoException (util.js:873:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at nextTickCallbackWith2Args (node.js:442:9)
        at process._tickDomainCallback (node.js:397:17)
    /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:93
          var condition = watch.condition.script.script;
                                                ^

    TypeError: Cannot read property 'script' of undefined
        at watching (/opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:76:51)
        at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:64:69
        at [object Object].scheduleTimeout [as _onTimeout] (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:846:9)
        at Timer.listOnTimeout (timers.js:92:15)

The reporter causing the error (although I suspect they all are);

    {
      "_index": "watcher",
      "_type": "watch",
      "_id": "cluster_health_watch",
      "_score": 1,
      "_source": {
        "trigger": {
          "schedule": {
            "later": "every 3 minutes"
          }
        },
        "input": {
          "search": {
            "request": {
              "indices": [
                "filebeat-*"
              ],
              "body": {
                "query": {
                  "template": {
                    "inline": {
                      "match": {
                        "NginxResponse": "{{query_string}}"
                      }
                    },
                    "params": {
                      "query_string": "\"MISS\"",
                      "filter": {
                        "range": {
                          "@timestamp": {
                            "from": "now-7d"
                          }
                        }
                      }
                    }
                  }
                },
                "aggs": {
                  "sum_kbytes": {
                    "sum": {
                      "field": "KBytes"
                    }
                  },
                  "avg_kbytes": {
                    "avg": {
                      "field": "KBytes"
                    }
                  }
                }
              }
            }
          }
        },
        "condition": {
          "script": {
            "script": "payload.hits.total > 0"
          }
        },
        "transform": {},
        "actions": {
          "report_admin": {
            "report": {
              "to": "me@site.com",
              "from": "Reports@site.com",
              "subject": "Misses Test",
              "priority": "high",
              "body": "Total Misses: {{payload.hits.total}} , Totalling: {{payload.aggregations.sum_kbytes.value}} KB",
              "snapshot": {
                "res": "1420x1420",
                "url": "http://google.com",
                "path": "/tmp/",
                "params": {
                  "username": "username",
                  "password": "userpass",
                  "delay": 5000,
                  "crop": false
                }
              }
            }
          }
        }
      }
    }

2. Reproducing the Issue step-by-step
a. [Install KaaE](https://github.com/elasticfence/kaae#app-installation) 
b. [install a few additional npm packages](http://stackoverflow.com/questions/28062060/npm-start-returns-error-127-while-setting-up-angular-seed-application/39840878#39840878) (some snapshots failed to render visualizations until I'd install these)
c. [Update config](https://github.com/elasticfence/kaae/wiki/KAAE-Config-Example#kaae-example-config) including kaae.json 
d. [Create a reporter ](https://github.com/elasticfence/kaae/wiki/KAAE-Report-Example#kaae-reports)(as in my case, it successfully ran until I attempted an uninstall/reinstall)
e. [uninstall KaaE](https://github.com/elasticfence/kaae#dev-plugin-remove)
f. reinstall KaaE (using same steps as before), your watchers should automatically show up unless you explicitly deleted them
g. wait for a report to fire, for me, this is when Kibana would tip over

3. Expected Results vs. Actual Results

4. Additional Details
I attempted this on two different machines, with the same result. The reason I initially attempted to reinstall was due to receiving bogus errors with later.js;

<code>
    Unhandled rejection Error: Missing schedule definition.
    at Object.later.schedule     (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:622:23)
▽
        at Object.later.setTimeout (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:810:19)
    at Object.later.setInterval (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:843:19)
    at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:64:45
    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3345:13)
    at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:37:9
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate]     (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
<!code>

However a reinstall didn't help at all, as that's when I started seeing other issues, such as [watchers not clearing](https://github.com/elasticfence/kaae/issues/33) and this issue.

OS: Ubuntu 14.04.3
ES: 2.4.1
Kibana: 4.6.1

Please let me know if I can assist in resolving this issue at all, I'm not great with angular.js but I will do my best to assist where I can.

Thanks for a great tool! I'm excited to get it working again.

**Comment by lmangani** [comment]
The watcher seems to be missing the ```condition``` fields and consequently fill fail to execute.
Could you confirm what you see in the watcher editor for this specific one?

**Comment by lmangani** [comment]
@sethyes are you running the above on a single ES node or cluster?

**Comment by sethyes** [comment]
This is running on a five-node cluster, specifically on the client node (master: false, data: false), which is a VM, but the same issue occurred on my other Kibana instance, which is a master-eligible node in the same cluster, a physical machine. 

@lmangani, this occurs for all three watchers I have set up, my original post had one watcher as seen from the editor (let me know if this isn't what you're looking for), however Kibana fell over when trying to run this watcher today (watcher editor contents below).

    {
      "_index": "watcher",
      "_type": "watch",
      "_id": "reporter_misses",
      "_score": 1,
      "_source": {
        "trigger": {
          "schedule": {
            "later": "every 3 minutes"
          }
        },
        "input": {
          "search": {
            "request": {
              "indices": [
                "filebeat-*"
              ],
              "body": {
                "query": {
                  "template": {
                    "inline": {
                      "match": {
                        "NginxResponse": "{{query_string}}"
                      }
                    },
                    "params": {
                      "query_string": "\"MISS\"",
                      "filter": {
                        "range": {
                          "@timestamp": {
                            "from": "now-7d"
                          }
                        }
                      }
                    }
                  }
                },
                "aggs": {
                  "sum_kbytes": {
                    "sum": {
                      "field": "KBytes"
                    }
                  },
                  "avg_kbytes": {
                    "avg": {
                      "field": "KBytes"
                    }
                  }
                }
              }
            }
          }
        },
        "condition": {},
        "transform": {},
        "actions": {
          "report_admin": {
            "report": {
              "to": "me@site.com",
              "from": "you@site.com",
              "subject": "Misses Test",
              "priority": "high",
              "body": "My watcher alert data",
              "snapshot": {
                "res": "1420x1420",
                "url": "http://google.com",
                "path": "/tmp/",
                "params": {
                  "username": "kaaeuser",
                  "password": "kaaepassword",
                  "delay": 5000,
                  "crop": false
                }
              }
            }
          }
        }
      }
    }

kibana.stdout:

    {"type":"log","@timestamp":"2016-10-06T14:03:00Z","tags":["status","debug","KaaE"],"pid":22536,"message":"Reloading Watchers..."}
    {"type":"log","@timestamp":"2016-10-06T14:03:00Z","tags":["status","info","KaaE"],"pid":22536,"message":"Executing watch: reporter_misses Next Round     of reporter_misses at Thu Oct 06 2016 08:03:00 GMT-0600 (MDT)"}
    {"type":"log","@timestamp":"2016-10-06T14:03:00Z","tags":["status","debug","KaaE","WATCHER DEBUG"],"pid":22536,"message":"{ _index: 'watcher',\n      _type: 'watch',\n  _id: 'reporter_misses',\n  _score: 1,\n  _source: \n   { trigger: { schedule: [Object] },\n     input: { search: [Object] },\n         condition: {},\n     transform: {},\n     actions: { report_admin: [Object] } } }"}    

kibana.stderr:

    Unhandled rejection Error: spawn phantomjs ENOENT
        at exports._errnoException (util.js:873:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at nextTickCallbackWith2Args (node.js:442:9)
        at process._tickDomainCallback (node.js:397:17)
    /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:93
              var condition = watch.condition.script.script;
                                                    ^
    
    TypeError: Cannot read property 'script' of undefined
        at watching (/opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:76:51)
        at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:64:69
        at [object Object].scheduleTimeout [as _onTimeout] (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:846:9)
        at Timer.listOnTimeout (timers.js:92:15)


As always, please let me know how I can help!

**Comment by sethyes** [comment]
I added the condition field to this specific watcher and it appears to still be failing on the same watcher.

    "condition": {
      "script": {
        "script": "payload.hits.total > 100"
      }
    }

**Comment by lmangani** [comment]
@sethyes Thanks for the update! The current error suggests the report is running but not able to spawn - is phantomjs installed on the system running KaaE? This is not included in the package (yet) only the ```node-horseman``` binding

**Comment by sethyes** [comment]
Of course -- I forgot to install phantomjs on this machine, thanks!
