### ISSUE TITLE
Report Changes Indicate 'Saved', yet Changes Don't Persist

### ISSUE THREAD

**Issue by sethyes** [elasticfence/kaae#35]
Issue;
When I create a report, many of the initial changes will save, however at a certain point, they won't anymore -- I'm unsure if this is due to the amount of data being saved or what -- additionally, if I try to save the changes to a new report, the report doesn't save. I'm sure it's a lot of work, but it'd be nice if it wasn't going to save for some reason, it would at least indicate that, even if it can't give a reason. 

For instance, the issue I'm experiencing right now is that if I attempt to modify my current report, the banner will appear at the top indicating my changes were saved, but opening the report, the changes did not actually save. Additionally, I can make a new report with the same data in it (_ID modified so as to not overwrite) and the same data is available, however a change as simple as adding a word to the subject line doesn't save -- if I try to modify the new saved report, the changes simply don't persist, if I try to change the values before saving the new report, the new report doesn't save at all. However the banner does appear and indicates the changes did save. 

To reproduce the issue; 

Create a report, add some complexity to it -- in my case I'd add much JS logic to the Transform script, reference those values in the report body. At a certain point, the changes no longer persist. You'll know the changes won't persist if you're tailing the kibana.stdout log, as you'll never see the message: "Saving Watcher with ID: ... "

 Expected Results vs. Actual Results

You'd expect the changes to either save or receive an error, even if internal, that they did not save. In reality, you are informed through the GUI that the changes did save, however looking at the logs or the watcher editor, you'll notice the changes never did save. 

 Additional Details

This seems to occur on a report-by-report basis -- I can modify a less-complex report on the same KaaE instance with no issue, however once they gain some complexity, something is hindering the save process. A copy of the problematic watcher is below, all the data does render properly, however please feel free to critique my humongous run on JS in the Transform Script;

    {
      "_index": "watcher",
      "_type": "watch",
      "_id": "watcher_report_by_layer_all_stats2",
      "_score": 1,
      "_source": {
        "trigger": {
          "schedule": {
            "later": "every 2 minutes"
          }
        },
        "input": {
          "search": {
            "request": {
              "indices": [
                "<filebeat-*>"
              ],
              "body": {
                "size": 0,
                "query": {
                  "filtered": {
                    "query": {
                      "query_string": {
                        "analyze_wildcard": true,
                        "query": "+type: \"nginx-access\" AND (nResponse: HIT OR nResponse: MISS OR nResponse: EXPIRED)"
                      }
                    },
                    "filter": {
                      "range": {
                        "@timestamp": {
                          "from": "now-7d"
                        }
                      }
                    }
                  }
                },
                "aggs": {
                  "2": {
                    "terms": {
                      "field": "nResponse",
                      "size": 5,
                      "order": {
                        "1": "desc"
                      }
                    },
                    "aggs": {
                      "1": {
                        "sum": {
                          "field": "Bytes"
                        }
                      },
                      "3": {
                        "terms": {
                          "field": "Streetside",
                          "size": 5,
                          "order": {
                            "1": "desc"
                          }
                        },
                        "aggs": {
                          "1": {
                            "sum": {
                              "field": "Bytes"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "condition": {
          "script": {
            "script": "payload.hits.total > 100"
          }
        },
        "transform": {
          "script": {
            "script": "payload.aerialhits = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"HIT\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Aerial\"; })[0].doc_count) / 1000000; payload.aerialhitsm = Math.round(payload.aerialhits * 10) / 10; payload.sshits = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"HIT\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Streetside\"; })[0].doc_count) / 1000000; payload.sshitsm = Math.round(payload.sshits * 10) / 10; payload.totalhittbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"HIT\"; })[0][1].value) / 1000000000000; payload.totalhittb = Math.round(payload.totalhittbytes * 10) / 10; payload.totalmisstbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"MISS\"; })[0][1].value) / 1000000000000; payload.totalmisstb = Math.round(payload.totalmisstbytes * 10) / 10; payload.totalexpiredtbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"EXPIRED\"; })[0][1].value) / 1000000000000; payload.totalexpiredtb = Math.round(payload.totalexpiredtbytes * 10) / 10; payload.hitratebytes = (payload.totalhittbytes / (payload.totalhittbytes + payload.totalmisstbytes + payload.totalexpiredtbytes)); payload.hitratebytesperc = Math.round(payload.hitratebytes * 1000) / 10 ; payload.tbrequested = Math.round((payload.totalhittb + payload.totalmisstb + payload.totalexpiredtb) *100) /100; payload.aerialhittbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"HIT\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Aerial\"; })[0][1].value) / 1000000000000; payload.aerialhittb = Math.round(payload.aerialhittbytes *10) / 10; payload.aerialmisstbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"MISS\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Aerial\"; })[0][1].value) / 1000000000000; payload.aerialmisstb = Math.round(payload.aerialmisstbytes *10) / 10; payload.aerialexpiredtbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"EXPIRED\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Aerial\"; })[0][1].value) / 1000000000000; payload.aerialexpiredtb = Math.round(payload.aerialexpiredtbytes *10) / 10; payload.aerialhitratebytes = (payload.aerialhittbytes / (payload.aerialhittbytes + payload.aerialmisstbytes + payload.aerialexpiredtbytes)) ; payload.aerialhitratedata = Math.round(payload.aerialhitratebytes * 1000) / 10; payload.streetsidehitgbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"HIT\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Streetside\"; })[0][1].value) / 1000000000; payload.streetsidehitgigs = Math.round(payload.streetsidehitgbytes *10) / 10; payload.streetsidemissgbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"MISS\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Streetside\"; })[0][1].value) / 1000000000; payload.streetsidemissgigs = Math.round(payload.streetsidemissgbytes *10) / 10; payload.streetsideexpiredgbytes = (payload.aggregations['2'].buckets.filter(function( obj ) { return obj.key == \"EXPIRED\"; })[0][3].buckets.filter(function( obj ) { return obj.key == \"Streetside\"; })[0][1].value) / 1000000000; payload.streetsideexpiredgigs = Math.round(payload.streetsideexpiredgbytes *10) / 10; payload.sshitratebytes = (payload.streetsidehitgbytes / (payload.streetsidehitgbytes + payload.streetsidemissgbytes + payload.streetsideexpiredgbytes)); payload.sshitratedata = Math.round(payload.sshitratebytes *1000) / 10;"
          }
        },
        "actions": {
          "report_admin": {
            "throttle_period": "15m",
            "report": {
              "to": "me@site.com",
              "from": "reports@site.com",
              "subject": "Cache Data Stats: {{payload.hitratebytesperc}}% test 2",
              "priority": "high",
              "body": " Total aerial hits: {{payload.aerialhitsm}} Million, total streetside hits: {{payload.sshitsm}} Million, Total data hit: {{payload.totalhittb}}TB, Total missed data: {{payload.totalmisstb}}TB, Total expired data: {{payload.totalexpiredtb}}TB, Data Hit Rate: {{payload.hitratebytesperc}}% of {{payload.tbrequested}}TB Total. ----- Total Aerial Data Hit: {{payload.aerialhittb}}TB, Missed: {{payload.aerialmisstb}}TB, Expired: {{payload.aerialexpiredtb}}TB, Aerial Hit Rate: {{payload.aerialhitratedata}}%. Streetside Data Hit: {{payload.streetsidehitgigs}}GB, Missed: {{payload.streetsidemissgigs}}GB, Expired: {{payload.streetsideexpiredgigs}}, Streetside Hit Rate: {{payload.sshitratedata}}%. ",
              "snapshot": {
                "res": "1420x1420",
                "url": "http://127.0.0.1/app/kibana#/dashboard/Hit-Rate-Per-Layer-Operators-Report",
                "path": "/tmp/",
                "params": {
                  "username": "kaaeuser",
                  "password": "kaaepassword",
                  "delay": 60000,
                  "crop": false
                }
              }
            }
          }
        }
      }
    }    

As always, thanks for a great tool! I am very excited for this functionality!

**Comment by lmangani** [comment]
@sethyes this would suggest the watcher not being accepted due to parsing errors - just guessing but it seems the most likely option, unless you also cannot save a blank, default watcher following one such event. Will try add more conditions to check and only fire the save confirmation when successful in the next releases.

**Comment by lmangani** [comment]
Please recheck using the latest build and try replicate the issue - thanks @sethyes for your report & support!

**Comment by sethyes** [comment]
@lmangani This appears to be fixed, I can add all sorts of bogus stuff to a watcher now, where it wouldn't save prior but now it does. This is better for me, so at least I can save developmental changes and if they don't work, I still have the code to modify and don't have to start from the last-working fix.

**Comment by lmangani** [comment]
Thanks @sethyes for confirming! Will add a "test now" functionality soon to play and debug watchers
