### ISSUE TITLE
Kaae dropdown crashes chrome

### ISSUE THREAD

**Issue by igaskin-gpsw** [elasticfence/kaae#39]
When clicking the dropdown in Kibana for "Watcher Script - Available Keys:"  the browser hangs and ultimately crashes.  I have not set up any watcher scripts, so this might be a contributing factor.  I have been able to consistently recreate the problem by clicking the dropdown.  Any ideas how to resolve this?

Kibana:
Version	4.5.4
Build	10000

Google Chrome	53.0.2785.143 (Official Build) (64-bit)
Revision	f33d44362232c20d1ce2111c53ea8730698f3c88-refs/branch-heads/2785@{#925}
OS	Mac OS X

**Comment by lmangani** [comment]
Hi @igaskin-gpsw and thanks for your report!
The dropdown iterates over the arrays available in the response body. 
Any chance you could provide the response which causes the crash here or privately?

**Comment by igaskin-gpsw** [comment]
Hi @lmangani I was not able to capture the response, because the chrome debugging tools became inoperable when I clicked the dropdown.  I copied the entire Google Chrome crash report, and uploaded it here: http://pastebin.com/raw/zLdFvSck

If you have suggestions regarding how to capture the response, please let me know.

**Comment by lmangani** [comment]
hi @igaskin-gpsw 
Just copy-paste the Response content from the SPY field itself please

**Comment by lmangani** [comment]
Please reopen if you can still reproduce this issue
