### ISSUE TITLE
How to use Console action?

### ISSUE THREAD

**Issue by maxout123** [elasticfence/kaae#41]
Trying to use Console action to debug watchers.

In Watcher:

```
    "actions": {
      "console_admin": {
        "console": {
          "priority": "high",
          "message": "Found Events {{payload.hits.total}}"
        }
      }
    }
```

In log:

```
Oct 12 07:53:20  kibana[21608]: {"type":"log","@timestamp":"2016-10-12T11:53:20Z","tags":["status","info","KaaE"],"pid":21608,"message":"Executing watch: maxouttest Next Round of maxouttest at Wed Oct 12 2016 07:53:20 GMT-0400 (EDT)"}
Oct 12 07:53:20  kibana[21608]: {"type":"log","@timestamp":"2016-10-12T11:53:20Z","tags":["status","info","KaaE"],"pid":21608,"message":"Action Report requires Email Settings! Reports Disabled."}
Oct 12 07:53:20  kibana[21608]: {"type":"log","@timestamp":"2016-10-12T11:53:20Z","tags":["status","info","KaaE"],"pid":21608,"message":"Processing action: console_admin"}
Oct 12 07:53:20  kibana[21608]: {"type":"log","@timestamp":"2016-10-12T11:53:20Z","tags":["status","info","KaaE"],"pid":21608,"message":"Console Payload: [object Object]"}
Oct 12 07:53:20  kibana[21608]: {"type":"log","@timestamp":"2016-10-12T11:53:20Z","tags":["status","info","KaaE"],"pid":21608,"message":"Storing Alarm to ES with type:console_admin"}
```

What's the `Console Payload: [object Object]` ?
Is it possible to see action's message in log? Debugging watchers through emails is so weird.

**Comment by lmangani** [comment]
Hi @maxout123 the output should be the actual object in console with the last commit.

Keep in mind every action by default is disabled and logs to console - so the console action is sort of redundant if you want to just test forming mustache output and matching conditions. If you provision an email watcher and leave delivery disabled in ```kaae.json``` it will only log to console.

**Comment by maxout123** [comment]
Doesn't work in latest, prints empty string:

Oct 12 08:17:10  kibana[26089]: {"type":"log","@timestamp":"2016-10-12T00:00:00Z","tags":["status","info","KaaE"],"pid":26089,"message":"Console Payload:"}

As for email watcher..
It will be very useful if I can see all the data in console, like it's printed at Alarm History page. With email watcher + delivery disabled I will see only message, not the whole alarm.

**Comment by lmangani** [comment]
My bad. Payload now Stringified and should display in console.

**Comment by maxout123** [comment]
That's strange, but output still the same.
I've double-checked and pretty sure I am using latest code

**Comment by maxout123** [comment]
Last commit you've made fixed display in console, thanks!

```
Oct 13 01:45:00  kibana[2549]: {"type":"log","@timestamp":"2016-10-13T05:45:00Z","tags":["status","info","KaaE"],"pid":2549,"message":"Console Payload {\"took\":4,\"timed_out\":false,\"_shards\":{\"total\":5,\"successful\":5,\"failed\":0},\"hits\":{\"total\":2,\"max_score\":3.070116,\"hits\":[{\"_index\":\"tpbeat-2016.10.13\",\"_type\":\"filesystem\",\"_id\":\"AVe8jc7Z1kWpQ9yogbQq\",\"_score\":3.070116,\"_source\":{\"fs\":{\"device_name\":\"/dev/vda1\",\"total\":3570522112,\"used\":4359471104,\"used_p\":0.14,\"free\":27211051008,\"avail\":25583775744,\"files\":1966080,\"free_files\":1820163,\"mount_point\":\"/\"},\"coun\":1,\"beat\":{\"hostname\":\"h2\",\"name\":\"h2\"},\"@timestamp\":\"2016-10-13T05:39:50.451Z\",\"type\":\"filesystem\",\"@version\":\"1\",\"host\":\h2\",\"tags\":[\"beats_input_raw_event\"]}}]},\"aggregations\":{\"device_name\":{\"doc_count_error_upper_bound\":0,\"sum_other_doc_count\":0,\"buckets\":[\"key\":\"/\",\"doc_count\":2,\"used_p\":{\"value\":0.14000000059604645}}]}}}"}

```

Is there any way to get rid of escaping?
Can the output be more human-readable, ie multiline/formatted, just like in alarm history tab in gui?

**Comment by lmangani** [comment]
Well, that's what JSON.stringify does and the console log won't print objects as-is. Thanks for confirming the new status - Will improve this concept in upcoming versions.

**Comment by maxout123** [comment]
Message variables are not expanded, in alarm history I see just text: `Found Events {{payload.hits.total}}` or `{{ payload }}`
When using email alarm, variables are expanded ok.

**Comment by lmangani** [comment]
Fix pushed and sorry for missing those - console was hardly used before so I appreciate your feedback plenty.

**Comment by maxout123** [comment]
It shows `[object Object]` by default (with no message defined), but expanding definitely works now.
