### ISSUE TITLE
kaae.json config file location 

### ISSUE THREAD

**Issue by rakeshv1** [elasticfence/kaae#42]
Hi 

I have a question regarding the location of the kaae.json config file
The documentation says it can be loaded from `/etc/kaae.json`
but on installation kaae.json also exists in the `kibana/installedplugins/kaae/`
Which file does it use ? 

Thank you

**Comment by lmangani** [comment]
Hi @rakeshv1 & Thanks for giving KaaE a shot!

If a configuration file is found at ```/etc/kaae.json``` it will be preferred and used, keep in mind the one inside Kibana will be overwritten on updates. Soon we'll migrate to settings directly in the Kibana config to make it even simpler for users to manage kaae settings.
