### ISSUE TITLE
watchers disappear after refresh

### ISSUE THREAD

**Issue by alias2696** [elasticfence/kaae#47]
1. Issue Description
issues disappear after refresh.

2. Reproducing the Issue step-by-step
- create a watcher in kibana, save or save and edit, you can see the watcher in kaae but after refresh or click on another tab then go back, watcher is gone 

3. Expected Results vs. Actual Results
expecting to see the list of watcher.

4. Additional Details
running on centos 7.2 with kibana -> kibana-4.6.1-1.x86_64 and ES -> elasticsearch-2.4.1-1.noarch

thanks
P.

**Comment by lmangani** [comment]
Please provide the Kibana logs and/or Elasticsearch logs during the save action to begin troubleshooting

**Comment by alias2696** [comment]
http://screencast.com/t/HZDZWUjDDhW6
---------------
ES logs are empty
----------
Kibana logs: 
{"type":"response","@timestamp":"2016-10-14T22:38:08Z","tags":[],"pid":3846,"method":"get","statusCode":200,"req":{"url":"/app/kaae","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","referer":"http://10.1.10.117/app/kibana","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kibana"},"res":{"statusCode":200,"responseTime":7,"contentLength":9},"message":"GET /app/kaae 200 7ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:09Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/commons.style.css?v=10146","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"text/css,*/*;q=0.1","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /bundles/commons.style.css?v=10146 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:09Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/kaae.style.css?v=10146","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"text/css,*/*;q=0.1","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":304,"responseTime":4,"contentLength":9},"message":"GET /bundles/kaae.style.css?v=10146 304 4ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:09Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/commons.bundle.js?v=10146","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"*/*","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /bundles/commons.bundle.js?v=10146 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:10Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/kaae.bundle.js?v=10146","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"*/*","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /bundles/kaae.bundle.js?v=10146 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:11Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/installedPlugins/kaae/public/kaae_watch.svg","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"image/webp,image/*,*/*;q=0.8","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /bundles/installedPlugins/kaae/public/kaae_watch.svg 304 1ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:11Z","tags":[],"pid":3846,"method":"get","statusCode":304,"req":{"url":"/bundles/node_modules/font-awesome/fonts/fontawesome-webfont.woff2","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","origin":"http://10.1.10.117","if-modified-since":"Fri, 14 Oct 2016 21:31:34 GMT","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","accept":"*/*","referer":"http://10.1.10.117/bundles/commons.style.css?v=10146","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/bundles/commons.style.css?v=10146"},"res":{"statusCode":304,"responseTime":3,"contentLength":9},"message":"GET /bundles/node_modules/font-awesome/fonts/fontawesome-webfont.woff2 304 3ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:11Z","tags":[],"pid":3846,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/_mget?timeout=0&ignore_unavailable=true&preference=1476484681804","method":"post","headers":{"connection":"upgrade","host":"10.1.10.117","content-length":"62","accept":"application/json, text/plain, */*","origin":"http://10.1.10.117","kbn-version":"4.6.1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"POST /elasticsearch/_mget?timeout=0&ignore_unavailable=true&preference=1476484681804 200 4ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:11Z","tags":[],"pid":3846,"method":"get","statusCode":200,"req":{"url":"/api/kaae/example","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","accept":"application/json, text/plain, */*","kbn-version":"4.6.1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/kaae/example 200 2ms - 9.0B"}
{"type":"response","@timestamp":"2016-10-14T22:38:11Z","tags":[],"pid":3846,"method":"get","statusCode":200,"req":{"url":"/api/kaae/list","method":"get","headers":{"connection":"upgrade","host":"10.1.10.117","accept":"application/json, text/plain, */*","kbn-version":"4.6.1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","referer":"http://10.1.10.117/app/kaae","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://10.1.10.117/app/kaae"},"res":{"statusCode":200,"responseTime":6,"contentLength":9},"message":"GET /api/kaae/list 200 6ms - 9.0B"}

**Comment by lmangani** [comment]
We need to see the logs for the save action. I don't seems to be finding any in your logs, just a listing.

**Comment by alias2696** [comment]
the save action itself does not seem to generate any logs for both save and save + edit in .. 

Thanks
P.

**Comment by lmangani** [comment]
@alias2696 set yout logs to verbose to see debug info

**Comment by alias2696** [comment]
ive attached another video, logging is verbose now, from what i see the save button has no action attached. 
http://screencast.com/t/qkQDFlAm1fOT
chrome developer tools:
http://screencast.com/t/ScevgecDPpRF

**Comment by alias2696** [comment]
here is another one, http://screencast.com/t/eQpVOlwx49O - seems like the button is executing the href action which does nothing rather than the NG-click action makeAlarm().

**Comment by lmangani** [comment]
Sorry but a screencast is not going to help here. I need to see the console + kibana logs output in verbose mode while you execute the watcher creation sequence:

- Push SAVE + EDIT in KAAE from Kibana Spy
- Once KaaE opens to display the new watcher, edit the name of it and save it

KaaE will perform several actions. If writing fails to your cluster it might be due to a number of reasons.

**Comment by lmangani** [comment]
@alias2696 I understand now

```SAVE WATCHER``` from SPY will only save it locally to be later picked up by Kaae. 

You MUST edit & save the watcher from KaaE's editor directly or it will not persist.

**Comment by lmangani** [comment]
Changed button description to avoid confusion. Watchers can *only* be saved from KaaE itself
