### ISSUE TITLE
Webhook action

### ISSUE THREAD

**Issue by testovtest** [elasticfence/kaae#53]
When i create webhook action and try to send data from search like payload.hits.total or others i receive on remote host only text "payload.hits.total" and no data.
My actions config here:
"actions": {
      "webhook": {
        "throttle_period": "2m",
        "webhook": {
          "method": "POST",
          "host": "192.168.52.37",
          "port": 63710,
          "body" : "{{payload.watcher_id}}:{{payload.hits.total}}"
        }
      },
     At the same  time in email actions it works correctly.

**Comment by lmangani** [comment]
Thanks @testovtest for catching this! Mustache rendering should now be fine, please check using snapshot or rebuild/reinstall the plugin.

**Comment by lmangani** [comment]
Feel free to re-open this issue in case you still experience inconsistencies. Thanks for your report!

**Comment by testovtest** [comment]
Now it works good, thanks! But am i right, that if i specify {{payload}} to send in body, i should receive all events for this search? Or there is another way to send all data returned by search?

**Comment by lmangani** [comment]
@testovtest the only limitation is how mustache renders the object. We can think of adding an option to just push out the entire payload without processing if needed.
