### ISSUE TITLE
message is not a valid Message instance

### ISSUE THREAD

**Issue by ed4becky** [elasticfence/kaae#57]
trying to use the email feature and I get the message: "message is not a valid Message instance" in the log.  This occurs with email or email_html.

     "actions": {
      "console_output": {
        "console": {
          "priority": "ERROR",
          "message": "Found {{payload.hits.total}} Exceptions"
        }
      },
      "email_admin": {
        "email": {
          "to": "ed_thompson@premierinc.com",
          "subject": "KaaE Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Exceptions"
        }
      }
    }

**Comment by lmangani** [comment]
Hi @ed4becky 
You are simply missing the from field, which is mandatory to form a "Valid Message" in ```emailjs```
