### ISSUE TITLE
slack must be configured even if not using it.

### ISSUE THREAD

**Issue by ed4becky** [elasticfence/kaae#58]
I removed the slack section from my kaae.json, an dthe program threw errors looking for slack.active.  Appears there is no check to see if slack is defined before testing for the active flag.

Also,  using email_html requires that email be "active" as well

**Comment by lmangani** [comment]
@ed4becky the kaae.json settings are supposed to be left intact to enable/disable features correctly.
Configuration will soon be moved to the main ```kibana.yml``` to avoid such scenarios but for the time being you need to leave it intact and updated reflecting the version it is paired with.

As of ```email```` and ```email_html```  they both use the same settings for delivery, so consider them the same method. Mind this is also true when using reports delivered via email.

**Comment by lmangani** [comment]
Just leave the sections you do not wish to use ```disabled``` without removing them please, and all should work as planned. Thanks for your Report!

**Comment by ed4becky** [comment]
Thanks for getting back to me.  I accept your response
