### ISSUE TITLE
Unhandled rejection HeadlessError: Phantom immediately exited with: 0

### ISSUE THREAD

**Issue by krisko** [elasticfence/kaae#61]
Hi, I have setup everything as described, I'm getting emails from watcher, but when the reporting job is triggered I get this err:
Unhandled rejection HeadlessError: Phantom immediately exited with: 0
    at ChildProcess.immediateExit (/mnt/sdb1/krisko_data/folder/elkstack/kibana-4.6.3-linux-x86_64/installedPlugins/kaae/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Don't know much about JS. Do you have any clue what could be the issue here?

thanks

**Comment by lmangani** [comment]
Hi @krisko 
I am not familiar with ```node-phantom-simple``` but KAAE requires a with a full build of PhantomJS installed on the system only, ie: ```npm install phantomjs-prebuilt -g``` - Have you tried it or excluded it for some specific reason?

**Comment by lmangani** [comment]
@krisko could you confirm you installed with ``` npm install phantomjs-prebuilt -g```` and provide the report configuration generating the error?

**Comment by krisko** [comment]
yes, I've installed phantonjs-prebuild:

`$ npm install phantomjs-prebuilt -g                                                                                                                                                                   
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs
                                                                                                                                                                                                                    
> phantomjs-prebuilt@2.1.13 install /usr/lib/node_modules/phantomjs-prebuilt                                                                                                                                        
> node install.js                                                                                                                                                                                                   
                                                                                                                                                                                                                    
Considering PhantomJS found at /usr/bin/phantomjs                                                                                                                                                                   
Looks like an `npm install -g`                                                                                                                                                                                      
Could not link global install, skipping...                                                                                                                                                                          
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2                                                                                                                                   
Verified checksum of previously downloaded file                                                                                                                                                                     
Extracting tar contents (via spawned process)                                                                                                                                                                       
Removing /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom                                                                                                                                                       
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1479246639711/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom                             
Writing location.js file                                                                                                                                                                                            
Done. Phantomjs binary available at /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
/usr/lib
└── phantomjs-prebuilt@2.1.13 
`

**Comment by krisko** [comment]
node-horseman has phantom-simple as dependency 

└─┬ node-horseman@3.2.0 
  ├── bluebird@3.4.6 
  ├── clone@1.0.2 
  ├── cookies.txt@0.1.2 
  ├── data-uri-to-buffer@0.0.4 
  ├─┬ debug@2.3.2 
  │ └── ms@0.7.2 
  ├── defaults@1.0.3 
  └── node-phantom-simple@2.2.4

**Comment by lmangani** [comment]
We'll need to see the report configuration triggering the error. Does this happen with any URL or a specific one?

Also are you able to run PhantomJS at all with any other command line example? You might be missing some libraries on your OS or image, etc.

**Comment by krisko** [comment]
my report config is:
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "reporter_7jjjwm1gu",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "report": true,
    "transform": {},
    "actions": {
      "report_admin": {
        "throttle_period": "1m",
        "report": {
          "to": "mymail@gmail.com",
          "from": "mymail@gmail.com",
          "subject": "KaaE Report",
          "priority": "medium",
          "body": "Sample KaaE Screenshot Report",
          "snapshot": {
            "res": "1280x900",
            "url": "http://127.1.0.1:5601/app/kibana#/dashboard/mosDsb",
            "path": "/tmp/",
            "params": {
              "delay": 10,
              "crop": false
            }
          }
        }
      }
    }
  }
}

I'll try to test phantomJS...

**Comment by lmangani** [comment]
Do you have authentication or anything else which might be blocking the request? Would the PhantomJS instance (not Kibana itself) be able to reach that IP and/or can you curl it from the same host?

**Comment by krisko** [comment]
no auth, and kibana is reachable.
I get an error when trying to issue phantomjs

$ phantomjs 
This application failed to start because it could not find or load the Qt platform plugin "xcb".

probably some library missing... I'm trying to fix this.

**Comment by lmangani** [comment]
Thanks for the update @krisko 
Whats your OS/Version?

**Comment by krisko** [comment]
Archlinux (updated today)

**Comment by krisko** [comment]
solved...
krisko krisko $ echo $QT_QPA_PLATFORM
xcb
krisko krisko $ unset QT_QPA_PLATFORM
krisko krisko $ phantomjs 
phantomjs>

Strange, but I had to unset this variable, now it works.

**Comment by lmangani** [comment]
Thanks @krisko for confirming the solution
