### ISSUE TITLE
Unable to install plugin for 5.0.0 

### ISSUE THREAD

**Issue by sps90** [elasticfence/kaae#64]
1. Issue Description
I am trying to install the kaae-latest.tar.gz for the 5.0.0 stable release but with error as follows
![image](https://cloud.githubusercontent.com/assets/11362115/20443746/fc73e29e-ad82-11e6-863e-56e98105bd73.png)

TIA!

**Comment by lmangani** [comment]
@sps90 this is a known issue atm still working around trying to get the installer to work.

KaaE 5.x is barely started - If you want to test the current codebase just manually copy the plugin directory to your Kibana 5  ```/plugins``` and let us know your findings - thanks!
